import type { CSSProperties } from "react";
import { cn } from "@/lib/utils";
import styles from "@/components/effects/AutumnAtmosphere.module.css";
import {
  BotanicalGlyph,
  type BotanicalKind,
} from "@/components/effects/botanicals/BotanicalGlyphs";

export type AutumnLeafLayer = "bg" | "mid" | "fg";

export type AutumnLeafConfig = {
  id: string;
  layer: AutumnLeafLayer;
  kind: BotanicalKind;
  left: string;
  size: number;
  opacity: number;
  color: string;
  blur: string;
  rot: string;
  scale: number;
  duration: string;
  delay: string;
  drift: string;
  curve: string;
  spin: string;
  staticTop: string;
  hideOnMobile?: boolean;
};

export const HERO_LEAVES: AutumnLeafConfig[] = [
  // —— Background (soft atmosphere) ——
  {
    id: "b1",
    layer: "bg",
    kind: "maple",
    left: "4%",
    size: 34,
    opacity: 0.08,
    color: "#B45309",
    blur: "3.5px",
    rot: "-22deg",
    scale: 1,
    duration: "22s",
    delay: "-2s",
    drift: "40px",
    curve: "18px",
    spin: "55deg",
    staticTop: "10%",
  },
  {
    id: "b2",
    layer: "bg",
    kind: "oak",
    left: "18%",
    size: 42,
    opacity: 0.06,
    color: "#D97706",
    blur: "4.2px",
    rot: "14deg",
    scale: 1.1,
    duration: "26s",
    delay: "-8s",
    drift: "-48px",
    curve: "-22px",
    spin: "-62deg",
    staticTop: "36%",
    hideOnMobile: true,
  },
  {
    id: "b3",
    layer: "bg",
    kind: "dried",
    left: "42%",
    size: 28,
    opacity: 0.1,
    color: "#EA580C",
    blur: "3px",
    rot: "28deg",
    scale: 0.9,
    duration: "24s",
    delay: "-14s",
    drift: "52px",
    curve: "14px",
    spin: "70deg",
    staticTop: "20%",
  },
  {
    id: "b4",
    layer: "bg",
    kind: "maple",
    left: "64%",
    size: 38,
    opacity: 0.07,
    color: "#F59E0B",
    blur: "4px",
    rot: "-10deg",
    scale: 1.05,
    duration: "20s",
    delay: "-5s",
    drift: "-36px",
    curve: "20px",
    spin: "48deg",
    staticTop: "52%",
    hideOnMobile: true,
  },
  {
    id: "b5",
    layer: "bg",
    kind: "fragment",
    left: "82%",
    size: 22,
    opacity: 0.09,
    color: "#B45309",
    blur: "3.2px",
    rot: "36deg",
    scale: 0.85,
    duration: "18s",
    delay: "-11s",
    drift: "24px",
    curve: "-16px",
    spin: "-44deg",
    staticTop: "68%",
  },
  {
    id: "b6",
    layer: "bg",
    kind: "oak",
    left: "30%",
    size: 36,
    opacity: 0.05,
    color: "#D97706",
    blur: "5px",
    rot: "-30deg",
    scale: 1.15,
    duration: "28s",
    delay: "-18s",
    drift: "-30px",
    curve: "26px",
    spin: "80deg",
    staticTop: "8%",
    hideOnMobile: true,
  },

  // —— Middle ground (8–12 slow drifts) ——
  {
    id: "m1",
    layer: "mid",
    kind: "maple",
    left: "10%",
    size: 18,
    opacity: 0.32,
    color: "#EA580C",
    blur: "0.3px",
    rot: "8deg",
    scale: 0.95,
    duration: "14s",
    delay: "-1s",
    drift: "38px",
    curve: "12px",
    spin: "58deg",
    staticTop: "26%",
  },
  {
    id: "m2",
    layer: "mid",
    kind: "dried",
    left: "24%",
    size: 15,
    opacity: 0.36,
    color: "#F59E0B",
    blur: "0.2px",
    rot: "-18deg",
    scale: 0.88,
    duration: "16s",
    delay: "-6s",
    drift: "-32px",
    curve: "-14px",
    spin: "-50deg",
    staticTop: "44%",
    hideOnMobile: true,
  },
  {
    id: "m3",
    layer: "mid",
    kind: "oak",
    left: "38%",
    size: 20,
    opacity: 0.26,
    color: "#D97706",
    blur: "0.45px",
    rot: "20deg",
    scale: 1,
    duration: "13s",
    delay: "-10s",
    drift: "28px",
    curve: "18px",
    spin: "64deg",
    staticTop: "14%",
  },
  {
    id: "m4",
    layer: "mid",
    kind: "fragment",
    left: "52%",
    size: 12,
    opacity: 0.4,
    color: "#B45309",
    blur: "0.15px",
    rot: "-12deg",
    scale: 0.9,
    duration: "15.5s",
    delay: "-3s",
    drift: "-44px",
    curve: "10px",
    spin: "42deg",
    staticTop: "58%",
  },
  {
    id: "m5",
    layer: "mid",
    kind: "maple",
    left: "66%",
    size: 17,
    opacity: 0.3,
    color: "#EA580C",
    blur: "0.35px",
    rot: "24deg",
    scale: 1.05,
    duration: "14.8s",
    delay: "-8s",
    drift: "30px",
    curve: "-20px",
    spin: "-56deg",
    staticTop: "32%",
    hideOnMobile: true,
  },
  {
    id: "m6",
    layer: "mid",
    kind: "dried",
    left: "78%",
    size: 14,
    opacity: 0.38,
    color: "#F59E0B",
    blur: "0.2px",
    rot: "-6deg",
    scale: 0.86,
    duration: "12.5s",
    delay: "-13s",
    drift: "-22px",
    curve: "16px",
    spin: "46deg",
    staticTop: "72%",
  },
  {
    id: "m7",
    layer: "mid",
    kind: "oak",
    left: "2%",
    size: 13,
    opacity: 0.22,
    color: "#D97706",
    blur: "0.5px",
    rot: "40deg",
    scale: 0.8,
    duration: "17s",
    delay: "-12s",
    drift: "20px",
    curve: "-10px",
    spin: "-68deg",
    staticTop: "80%",
    hideOnMobile: true,
  },
  {
    id: "m8",
    layer: "mid",
    kind: "fragment",
    left: "88%",
    size: 11,
    opacity: 0.34,
    color: "#B45309",
    blur: "0.25px",
    rot: "16deg",
    scale: 0.92,
    duration: "13.8s",
    delay: "-4s",
    drift: "18px",
    curve: "12px",
    spin: "38deg",
    staticTop: "48%",
  },
  {
    id: "m9",
    layer: "mid",
    kind: "maple",
    left: "46%",
    size: 16,
    opacity: 0.28,
    color: "#EA580C",
    blur: "0.4px",
    rot: "-26deg",
    scale: 0.98,
    duration: "15s",
    delay: "-16s",
    drift: "-26px",
    curve: "22px",
    spin: "72deg",
    staticTop: "64%",
    hideOnMobile: true,
  },
  {
    id: "m10",
    layer: "mid",
    kind: "dried",
    left: "58%",
    size: 13,
    opacity: 0.33,
    color: "#F59E0B",
    blur: "0.3px",
    rot: "12deg",
    scale: 0.9,
    duration: "16.5s",
    delay: "-9s",
    drift: "34px",
    curve: "-12px",
    spin: "-40deg",
    staticTop: "22%",
  },

  // —— Foreground (near camera, mostly right / near portrait) ——
  {
    id: "f1",
    layer: "fg",
    kind: "maple",
    left: "60%",
    size: 34,
    opacity: 0.55,
    color: "#D97706",
    blur: "0px",
    rot: "-12deg",
    scale: 1.08,
    duration: "13s",
    delay: "-3s",
    drift: "22px",
    curve: "14px",
    spin: "48deg",
    staticTop: "40%",
  },
  {
    id: "f2",
    layer: "fg",
    kind: "oak",
    left: "76%",
    size: 28,
    opacity: 0.58,
    color: "#EA580C",
    blur: "0px",
    rot: "18deg",
    scale: 1,
    duration: "15s",
    delay: "-7s",
    drift: "-28px",
    curve: "-18px",
    spin: "-54deg",
    staticTop: "16%",
  },
  {
    id: "f3",
    layer: "fg",
    kind: "dried",
    left: "90%",
    size: 40,
    opacity: 0.48,
    color: "#B45309",
    blur: "0.25px",
    rot: "22deg",
    scale: 1.12,
    duration: "11s",
    delay: "-1s",
    drift: "16px",
    curve: "10px",
    spin: "66deg",
    staticTop: "56%",
    hideOnMobile: true,
  },
  {
    id: "f4",
    layer: "fg",
    kind: "maple",
    left: "8%",
    size: 22,
    opacity: 0.42,
    color: "#F59E0B",
    blur: "0.15px",
    rot: "-28deg",
    scale: 0.94,
    duration: "14s",
    delay: "-9s",
    drift: "-18px",
    curve: "12px",
    spin: "44deg",
    staticTop: "74%",
    hideOnMobile: true,
  },
];

export function AutumnLeaf({
  leaf,
  className,
}: {
  leaf: AutumnLeafConfig;
  className?: string;
}) {
  return (
    <span
      className={cn(styles.leaf, leaf.hideOnMobile && styles.leafMobileHide, className)}
      style={
        {
          "--leaf-left": leaf.left,
          "--leaf-size": `${leaf.size}px`,
          "--leaf-opacity": String(leaf.opacity),
          "--leaf-color": leaf.color,
          "--leaf-blur": leaf.blur,
          "--leaf-rot": leaf.rot,
          "--leaf-scale": String(leaf.scale),
          "--leaf-duration": leaf.duration,
          "--leaf-delay": leaf.delay,
          "--leaf-drift": leaf.drift,
          "--leaf-curve": leaf.curve,
          "--leaf-spin": leaf.spin,
          "--leaf-static-top": leaf.staticTop,
          color: leaf.color,
        } as CSSProperties
      }
    >
      <BotanicalGlyph kind={leaf.kind} className={styles.leafSvg} color={leaf.color} />
    </span>
  );
}
